version: "3.4"

services:
  technologiestiftungnextiothubapi:
    image: etherpad
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
